{{- if and .Values.rocketchat.enabled .Values.rocketchat.ingress.enabled .Values.rocketchat.ingress.hosts }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-rocketchat
  labels:
    app: rocketchat
spec:
  ingressClassName: {{ .Values.rocketchat.ingress.className }}
  rules:
    {{- range .Values.rocketchat.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $.Release.Name }}-rocketchat
                port:
                  number: {{ $.Values.rocketchat.service.port }}
          {{- end }}
    {{- end }}

{{- end }}
 
