{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mongo-pvc
  labels:
    app: mongodb
spec:
  storageClassName: {{ .Values.mongodb.persistence.storageClassName | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
{{- end }}
