{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-conf
  labels:
    app: nginx
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        resolver kube-dns.kube-system.svc.cluster.local valid=10s;
        server {
            listen 8080;
            server_name _;
            location / {
                set $upstream {{ .Values.nginx.upstream }};
                proxy_pass http://$upstream;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
{{- end }}
