{{- if .Values.rocketchat.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rocketchat
  labels:
    app: rocketchat
spec:
  type: {{ .Values.rocketchat.service.type }}
  ports:
    - port: {{ .Values.rocketchat.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: rocketchat
{{- end }}
