{{- if .Values.mongodb.enabled }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-mongodb-key" .Release.Name) }}
{{- $mongoKeyfile := "" }}
{{- if $existingSecret }}
  {{- $mongoKeyfile = index $existingSecret.data "mongo-keyfile" }}
{{- else }}
  {{- $mongoKeyfile = randAlphaNum 1024 | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-key
type: Opaque
data:
  mongo-keyfile: {{ $mongoKeyfile | quote }}
{{- end }}
{{- if or .Values.mongodb.enabled .Values.rocketchat.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rocketchat-secret
type: Opaque
data:
  mongo-root-user: {{ .Values.mongodb.auth.rootUser | b64enc | quote }}
  mongo-root-password: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
{{- end }}
