rocketchat:
  replicaCount: 1
  rootUrl: "http://rocketchat.local"
  image:
    repository: registry.rocket.chat/rocketchat/rocket.chat
    tag: 6.8.0
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    className: nginx
  service:
    type: ClusterIP
    port: 3000
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  resources:
    limits:
      cpu: "2.0"
      memory: "2Gi"
    requests:
      cpu: "500m"
      memory: "1Gi"
