nginx:
  tls:
    enabled: false
    secretName: nginx-tls
  enabled: true
  replicaCount: 1
  image:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    httpPort: 8080
    httpsPort: 8443
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
