rocketchat:
  enabled: true
  replicaCount: 1
  rootUrl: "http://<public_ip>.nip.io"
  imagePullSecrets:          # ← move here, NOT under image:
    - name: gar-secret
  image:
    repository: asia-south2-docker.pkg.dev/project-d3f73645-327e-4f11-ba2/rocketchat/rocketchat-app
    tag: "6.8.0"
    pullPolicy: Always
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: <public_ip>.nip.io   # change this
        paths:
          - path: /
            pathType: Prefix
  service:
    type: ClusterIP
    port: 3000
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  resources:
    limits:
      cpu: "2.0"
      memory: "2Gi"
    requests:
      cpu: "500m"
      memory: "1Gi"
  persistence:
    storageClassName: "standard-rwx"

mongodb:
  auth:
    rootUser: rocketchat
    rootPassword: verysecurepassword

nginx:
  enabled: true
  replicaCount: 1
  image:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    httpPort: 80
    httpsPort: 443
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"
