apiVersion: v2
name: rocketchat
description: A production-ready Helm chart for Rocket.Chat deployment based on the architectural diagram using an optimized Nginx Ingress, HPA, and StatefulSet MongoDB setup. Includes limits suitable for 8GB RAM, 4 Core environments.
type: application
version: 1.0.0
appVersion: "6.8.0"
